name: shoeproject_hive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  sqflite: ^2.3.0
    
  hive_flutter: ^1.1.0
  # hive_flutter: ^1.1.0
  hive: ^2.2.3
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  image_picker: ^1.0.5
    

dev_dependencies:
  flutter_test:
    sdk: flutter
   
  hive_generator: ^2.0.1
  # build_runner: ^2.4.6
  flutter_lints: ^3.0.1

  build_runner: ^2.1.4




flutter:

  
  uses-material-design: true
  generate: true
  assets:
    - Images/
